<a href="https://colab.research.google.com/github/BenFalken/ntx_project/blob/main/timestamps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
import numpy as np

In [ ]:
fs = 250

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
dir = "/content/drive/MyDrive/2023-2024 CruX/NTX Competition/Data/EEG Data/bill/"

In [ ]:
data = np.genfromtxt(dir + "bill.csv")

In [ ]:
vid_timestamps = np.genfromtxt(dir + "timestamps.csv", delimiter=',')

In [ ]:
vid_timestamps

array([[1.70970698e+09, 1.70970714e+09],
       [1.70970728e+09, 1.70970732e+09],
       [1.70970743e+09, 1.70970748e+09],
       [1.70970753e+09, 1.70970759e+09],
       [1.70970763e+09, 1.70970769e+09],
       [1.70970773e+09, 1.70970776e+09],
       [1.70970783e+09, 1.70970805e+09],
       [1.70970809e+09, 1.70970815e+09],
       [1.70970823e+09, 1.70970829e+09],
       [1.70970838e+09, 1.70970845e+09],
       [1.70970850e+09, 1.70970856e+09],
       [1.70970861e+09, 1.70970868e+09],
       [1.70970869e+09, 1.70970871e+09],
       [1.70970876e+09, 1.70970881e+09],
       [1.70970883e+09, 1.70970889e+09],
       [1.70970902e+09, 1.70970906e+09],
       [1.70970910e+09, 1.70970917e+09],
       [1.70970922e+09, 1.70970929e+09],
       [1.70970934e+09, 1.70970936e+09],
       [1.70970943e+09, 1.70970946e+09],
       [1.70970954e+09, 1.70970957e+09],
       [1.70970963e+09, 1.70970965e+09],
       [1.70970967e+09, 1.70970973e+09]])

In [ ]:
vid_timestamps_start = vid_timestamps[:, 0]
vid_timestamps_end = vid_timestamps[:, 1]

In [ ]:
type(data)

numpy.ndarray

In [ ]:
data.shape

(740329, 24)

In [ ]:
EEG_data = data[:, 1:9]

In [ ]:
EEG_data[0]

array([ 2232.805161,  1283.683036, 10517.792167, 13763.176055,
         700.526023,  9670.102259,  9822.451749,  6638.266938])

In [ ]:
data[0]

array([8.60000000e+01, 2.23280516e+03, 1.28368304e+03, 1.05177922e+04,
       1.37631761e+04, 7.00526023e+02, 9.67010226e+03, 9.82245175e+03,
       6.63826694e+03, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.92000000e+02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.70970689e+09, 0.00000000e+00])

In [ ]:
timestamps = data[:,22]
print(timestamps)

[1.70970689e+09 1.70970689e+09 1.70970689e+09 ... 1.70970985e+09
 1.70970985e+09 1.70970985e+09]


In [ ]:
timestamps[0]

1709706890.082852

In [ ]:
value = 1709706977.26357

In [ ]:
index = np.abs(timestamps - value).argmin()
print(index)

21888


In [ ]:
indices_start = []
for vid_timestamp in vid_timestamps_start:
  indices_start.append(np.abs(timestamps - vid_timestamp).argmin())

print(indices_start)

[21888, 98122, 134196, 158964, 184576, 210669, 234959, 300249, 334159, 372154, 403178, 431434, 451155, 467027, 486385, 533038, 553840, 584014, 612871, 634996, 662291, 685017, 696681]


In [ ]:
indices_end = []
for vid_timestamp in vid_timestamps_end:
  indices_end.append(np.abs(timestamps - vid_timestamp).argmin())

print(indices_end)

[62050, 108823, 148383, 174717, 200209, 218484, 289068, 314439, 349909, 390192, 417847, 446706, 454641, 481094, 500934, 543500, 570073, 600367, 616961, 644134, 670828, 690187, 709908]


In [ ]:
durations = (np.array(indices_end) - np.array(indices_start)) / fs / 60

In [ ]:
durations

array([2.67746667, 0.7134    , 0.9458    , 1.0502    , 1.0422    ,
       0.521     , 3.60726667, 0.946     , 1.05      , 1.20253333,
       0.97793333, 1.01813333, 0.2324    , 0.9378    , 0.96993333,
       0.69746667, 1.0822    , 1.0902    , 0.27266667, 0.6092    ,
       0.56913333, 0.34466667, 0.8818    ])